### ISSUE TITLE
error: ld returned 1 exit status

### ISSUE THREAD

**Issue by LvJC** [iamhankai/cpp-pytorch#2]
Hello, I wonder to know which CUDA and cudnn version in your project.

I am using CUDA9.0 cudnn7, but there's an error that occurred.
I am confused and guess if this is because I modified files using this:
https://medium.com/@mengjiunchiou/build-opencv-caffe-with-cuda-9-0-on-ubuntu-16-04-b2794a41612d
And I modified this way becuz OpenCV2.4 is incompatible with CUDA9.0.

Now this seems to bother me much more...

**Comment by iamhankai** [comment]
I test on CPU, not on CUDA. Sorry about that.
