### ISSUE TITLE
what is the meaning about this,thanks

### ISSUE THREAD

**Issue by by1024354288** [iamhankai/cpp-pytorch#5]
img_tensor[0][0] = img_tensor[0][0].sub_(0.485).div_(0.229);
img_tensor[0][1] = img_tensor[0][1].sub_(0.456).div_(0.224);
img_tensor[0][2] = img_tensor[0][2].sub_(0.406).div_(0.225);

**Comment by iamhankai** [comment]
Removing mean values of the RGB channels. The values are taken from https://github.com/pytorch/examples/blob/master/imagenet/main.py#L194
