### ISSUE TITLE
what is the function about this part

### ISSUE THREAD

**Issue by by1024354288** [iamhankai/cpp-pytorch#6]
this part is neccesary ,can i remove it only leave "  std::vector<torch::jit::IValue> inputs;"

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::rand({64, 3, 224, 224}));

  module->forward(inputs).toTensor();
  inputs.pop_back();

**Comment by iamhankai** [comment]
Emm...
without `inputs.push_back(torch::rand({64, 3, 224, 224}));`, the inputs are empty and the CNN has no inputs.

**Comment by by1024354288** [comment]
I mean this:
  std::vector<torch::jit::IValue> inputs;
  auto img_var = torch::autograd::make_variable(img_tensor, false);
  inputs.push_back(img_var);

**Comment by iamhankai** [comment]
I think the API donot support that. You can have a try.
